version: '3'

services:

  php:
    build:
      context: .
    volumes:
      - ./:/app/
    tty: true

  postgres:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
